### ISSUE TITLE
Global datasets: shown different icon instead of bounds

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/wamedex#12]
https://gwf-uwaterloo.github.io/wamedex/#13079_iso.xml

<img width="553" alt="Screen Shot 2019-05-10 at 5 10 57 PM" src="https://user-images.githubusercontent.com/313837/57557012-9a96f480-7346-11e9-9168-d88db936877b.png">

Instead of showing bounds, which is a bit silly because it's the entire globe... let's just replace the pin with a 🌍 icon or something similar...

**Comment by Alex-Weatherhead** [comment]
Fixed with 01e400f

**Comment by gauchm** [comment]
Done.
