### ISSUE TITLE
Add "show all bounds" and "hide all bounds" option.

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/wamedex#5]
Should appear at the top of all the cards.

**Comment by lintool** [comment]
> Maybe the Location-marker icon? (Such as https://material.io/tools/icons/?icon=location_on&style=baseline and https://material.io/tools/icons/?icon=location_off&style=baseline)

👍 

Also use these icons in each card?

**Comment by gauchm** [comment]
Added with 495bede.

**Comment by lintool** [comment]
Nice!
