### ISSUE TITLE
Refine descriptive keywords display

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/wamedex#6]
<img width="456" alt="Screen Shot 2019-04-20 at 9 21 39 PM" src="https://user-images.githubusercontent.com/313837/56464223-a3814f80-63b2-11e9-973a-b7d0c909d28c.png">

**TODO**

- refine spacing in list of keywords
- add link to thesaurus name

**Comment by gauchm** [comment]
Fixed with d772224.

**Comment by lintool** [comment]
Thanks!
